// library/packages/qwik/src/greet/greet.tsx
import { $, Fragment, component$, h, useStore } from "@builder.io/qwik";

export const Greet = component$((props: any) => {
  const state = useStore<any>({ name: "Mati" });

  return (
    <div>
      <input
        placeholder="Your name"
        value={state.name}
        onChange$={$((event) => (state.name = event.target.value))}
      />
      <div>Hello, {state.name}!</div>
    </div>
  );
});

export default Greet;

// library/packages/react/src/greet/greet.tsx
"use client";
import * as React from "react";
import { useState } from "react";

function Greet(props: any) {
  const [name, setName] = useState(() => "Mati");

  return (
    <div>
      <input
        placeholder="Your name"
        value={name}
        onChange={(event) => setName(event.target.value)}
      />
      <div>Hello, {name}!</div>
    </div>
  );
}

export default Greet;
